/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin;


import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Container;

/**
 *
 * @author Desktop-Putri
 */
public class MenuUtama extends javax.swing.JFrame {

    private Container admin;

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        
        CardLayout card = (CardLayout)(mainPanel.getLayout());
        // Ubah layout mainPanel jadi CardLayout
    mainPanel.setLayout(new java.awt.CardLayout());
    
  // BUAT OBJEK DARI PANEL2
    PanelHome panelHome = new PanelHome();
    PanelPengguna panelPengguna = new PanelPengguna();
    PanelLaporan panelLaporan = new PanelLaporan();
    PanelMenu panelMenu = new PanelMenu();
    
    // TAMBAHKAN KE mainPanel
    mainPanel.add(panelHome, "PanelHome");
    mainPanel.add(panelPengguna, "PanelPengguna");
    mainPanel.add(panelLaporan, "PanelLaporan");
    mainPanel.add(panelMenu, "PanelMenu");
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        konsul = new javax.swing.JLabel();
        sehat = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        keluar = new javax.swing.JLabel();
        pengguna = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(204, 255, 204));

        konsul.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        konsul.setForeground(new java.awt.Color(51, 51, 51));
        konsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leaf.png"))); // NOI18N
        konsul.setText("KONSULTASI");

        sehat.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        sehat.setForeground(new java.awt.Color(51, 51, 51));
        sehat.setText("SEHAT");
        sehat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        menu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/healthy-food.png"))); // NOI18N
        menu.setText("Data Menu Makanan");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        laporan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profit-report.png"))); // NOI18N
        laporan.setText("Laporan Konsultasi");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        pengguna.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user(1).png"))); // NOI18N
        pengguna.setText("Data Pengguna");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(konsul))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(sehat, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu)
                            .addComponent(pengguna)
                            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(konsul)
                .addGap(0, 0, 0)
                .addComponent(sehat)
                .addGap(37, 37, 37)
                .addComponent(pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 321, 570));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(955, 588));
        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 840, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "PanelMenu");
    }//GEN-LAST:event_menuMouseClicked

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "PanelPengguna");
    }//GEN-LAST:event_penggunaMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "PanelLaporan");
    }//GEN-LAST:event_laporanMouseClicked

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
   int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Yakin ingin keluar ke halaman login?", 
        "Konfirmasi", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        new login().setVisible(true);  // buka form login
        this.dispose();                 // tutup menu utama
    }

    }//GEN-LAST:event_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel konsul;
    private javax.swing.JLabel laporan;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menu;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel pengguna;
    private javax.swing.JLabel sehat;
    // End of variables declaration//GEN-END:variables
}
