/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna;

import admin.koneksi;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Desktop-Putri
 */
public class PanelKonsultasi extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelKonsultasi
     */
    
    private MenuUtamaPengguna parent;

public PanelKonsultasi(MenuUtamaPengguna parent) {
    this.parent = parent;
    initComponents();
}

public void resetForm() {
    inputbb.setText("");
    inputtb.setText("");
    aktivitas.setSelectedIndex(0); // pilih item pertama

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputbb = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        inputtb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aktivitas = new javax.swing.JComboBox<>();
        bproses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 29)); // NOI18N
        jLabel1.setText("Form Konsultasi Nutrisi");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exam (1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel3.setText("Berat Badan (kg) :");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel4.setText("Tinggi Badan (cm) :");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setText("Aktiivitas :");

        aktivitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Aktivitas", "Ringan", "Sedang", "Berat", " " }));
        aktivitas.setToolTipText("");

        bproses.setBackground(new java.awt.Color(0, 0, 153));
        bproses.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        bproses.setForeground(new java.awt.Color(255, 255, 255));
        bproses.setText("Proses Konsultasi");
        bproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprosesActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/restaurant.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/healthcare.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bproses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(aktivitas, 0, 324, Short.MAX_VALUE)
                                    .addComponent(inputbb, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputtb, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputbb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputtb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(bproses, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprosesActionPerformed
   try {
        double bb = Double.parseDouble(inputbb.getText());
        double tb = Double.parseDouble(inputtb.getText()) / 100;
        String aktivitasUser = aktivitas.getSelectedItem().toString();

        double bmi = bb / (tb * tb);

        String kategori;
        if (bmi < 18.5) {
            kategori = "Kurus";
        } else if (bmi < 25) {
            kategori = "Normal";
        } else {
            kategori = "Gemuk";
        }

        double kalori = 24 * bb;
        if (aktivitasUser.equals("Ringan")) {
            kalori *= 1.3;
        } else if (aktivitasUser.equals("Sedang")) {
            kalori *= 1.5;
        } else if (aktivitasUser.equals("Berat")) {
            kalori *= 1.7;
        }


        String saranMenu = "=== SARAN MENU MAKANAN ===\n";
        String sqlMenu;

        if (kalori < 1800) {
            sqlMenu = "SELECT nama, kalori, protein, karbo FROM menu_makanan WHERE kalori < 400 LIMIT 3";
        } else if (kalori <= 2200) {
            sqlMenu = "SELECT nama, kalori, protein, karbo FROM menu_makanan WHERE kalori BETWEEN 400 AND 700 LIMIT 3";
        } else {
            sqlMenu = "SELECT nama, kalori, protein, karbo FROM menu_makanan WHERE kalori > 700 LIMIT 3";
        }

        Connection conn = koneksi.getConnection();
        PreparedStatement pstMenu = conn.prepareStatement(sqlMenu);
        ResultSet rsMenu = pstMenu.executeQuery();

        while (rsMenu.next()) {
            saranMenu += "- " + rsMenu.getString("nama")
                    + " | Kalori: " + rsMenu.getInt("kalori")
                    + " | Protein: " + rsMenu.getInt("protein")
                    + " | Karbo: " + rsMenu.getInt("karbo") + "\n";
        }


if (parent == null) {
    JOptionPane.showMessageDialog(this, "Parent masih NULL!");
    return;
}
// simpan data ke frame
parent.bb = bb;
parent.tb = tb * 100;
parent.bmi = bmi;
parent.kalori = kalori;
parent.kategori = kategori;
parent.aktivitas = aktivitasUser;
parent.saranMenu = saranMenu;

// update panel hasil & beranda
parent.PanelHasil.tampilkanData();

// pindah panel
parent.showPanel("PanelHasil");


    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_bprosesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aktivitas;
    private javax.swing.JButton bproses;
    private javax.swing.JTextField inputbb;
    private javax.swing.JTextField inputtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
