/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna;

import admin.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Desktop-Putri
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        konfirmasi = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        view1 = new javax.swing.JLabel();
        view2 = new javax.swing.JLabel();
        hide2 = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jkonfirmasi = new javax.swing.JPasswordField();
        jemail = new javax.swing.JTextField();
        daftar = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DAFTAR AKUN BARU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 16, -1, -1));

        username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setText("Username");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 92, -1, -1));

        password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 158, -1, -1));

        konfirmasi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        konfirmasi.setForeground(new java.awt.Color(102, 102, 102));
        konfirmasi.setText("Konfirmasi Password");
        getContentPane().add(konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 226, -1, -1));

        email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("Email");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 286, -1, -1));

        juser.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        getContentPane().add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 237, 45));

        view1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view(1).png"))); // NOI18N
        view1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view1MouseClicked(evt);
            }
        });
        getContentPane().add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 40, 50));

        view2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view(1).png"))); // NOI18N
        view2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view2MouseClicked(evt);
            }
        });
        getContentPane().add(view2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 40, 50));

        hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide(1).png"))); // NOI18N
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide2MouseClicked(evt);
            }
        });
        getContentPane().add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 40, 50));

        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide(1).png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide1MouseClicked(evt);
            }
        });
        getContentPane().add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 40, 50));

        jpassword.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 153, 237, 45));

        jkonfirmasi.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        getContentPane().add(jkonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 221, 237, 45));

        jemail.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 281, 199, 45));

        daftar.setBackground(new java.awt.Color(0, 102, 51));
        daftar.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        daftar.setText("DAFTAR");
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 375, 161, 37));

        batal.setBackground(new java.awt.Color(0, 102, 51));
        batal.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 375, 164, 37));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
    String username = juser.getText().trim();
    String password = new String(jpassword.getPassword());
    String konfirmasi = new String(jkonfirmasi.getPassword());
    String email = jemail.getText().trim();

    if (username.isEmpty() || password.isEmpty() || konfirmasi.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return;
    }

    if (!password.equals(konfirmasi)) {
        JOptionPane.showMessageDialog(this, "Password dan Konfirmasi tidak sama!");
        return;
    }

    try {
        Connection conn = koneksi.getConnection();
        String sql = "INSERT INTO pengguna (username, password, email) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        pst.setString(2, password);
        pst.setString(3, email);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Akun berhasil didaftarkan! Silakan login.");
        this.dispose(); // tutup form daftar
        new loginn().setVisible(true); // kembali ke form login
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal daftar: " + e.getMessage());
    }

    }//GEN-LAST:event_daftarActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
   this.dispose(); // tutup form daftar
    new loginn().setVisible(true); // balik ke form login

    }//GEN-LAST:event_batalActionPerformed

    private void view2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view2MouseClicked
    
        jpassword.setEchoChar((char)0); // tampilkan password
        view2.setVisible(false);
        hide2.setVisible(true);
    }//GEN-LAST:event_view2MouseClicked

    private void hide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MouseClicked
        jpassword.setEchoChar('•'); // sembunyikan password
        hide2.setVisible(false);
        view2.setVisible(true);
    }//GEN-LAST:event_hide2MouseClicked

    private void view1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view1MouseClicked
        jkonfirmasi.setEchoChar((char)0); // tampilkan password
        view1.setVisible(false);
        hide1.setVisible(true);
    }//GEN-LAST:event_view1MouseClicked

    private void hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseClicked
        jkonfirmasi.setEchoChar('•'); // sembunyikan password
        hide1.setVisible(false);
        view1.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_hide1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton daftar;
    private javax.swing.JLabel email;
    private javax.swing.JLabel hide1;
    private javax.swing.JLabel hide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jemail;
    private javax.swing.JPasswordField jkonfirmasi;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField juser;
    private javax.swing.JLabel konfirmasi;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    private javax.swing.JLabel view1;
    private javax.swing.JLabel view2;
    // End of variables declaration//GEN-END:variables
}
